### PR TITLE
Use an OTA provider configuration list instead of per-manufacturer keys

### PR DESCRIPTION
**Pull request by puddly**
This format is backwards compatible with the old format but aims to be much more versatile:

```yaml
zha:
  zigpy_config:
    ota:
      enabled: true
      disable_default_providers: [ikea]
      # Replace all default providers by specifying `providers` instead of `extra_providers`
      extra_providers:
        - type: salus 
          url: https://example.org/salus.json
          override_previous: true  # Replace all previous Salus providers with this one
        - type: ikea  # DIRIGERA feed
        - type: ikea  # Old IKEA test feed
          url: https://fw.test.ota.homesmart.ikea.net/feed/version_info.json
        - type: ikea  # Old IKEA feed
          url: https://fw.ota.homesmart.ikea.net/feed/version_info.json
        - type: zigpy
          url: https://example.org/ota.json
          manufacturer_ids: [0x1234, 0x5678]  # Optional
        - type: z2m
        - type: z2m  # Use multiple providers of the same type
          url: https://some/other/index.json
        - type: z2m_local
          path: /path/to/index.json
        - type: advanced
          warning: I understand I can *destroy* my devices by enabling OTA updates from
            files. Some OTA updates can be mistakenly applied to the wrong
            device, breaking it. I am consciously using this at my own risk.
          path: /path/to/folder/of/otas
```

For those just interested in enabling updates from the Z2M repo, the config is:

```yaml
zha:
  zigpy_config:
    ota:
      extra_providers:
        - type: z2m
```

For manufacturers interested in testing a new feed URLs for their provider (CC @InovelliUSA @hwzolin), you can add a new provider that points to it:

```yaml
zha:
  zigpy_config:
    ota:
      extra_providers:
        - type: inovelli
          url: https://files.inovelli.com/firmware/firmware-zha-for-testing.json
          override_previous: true
```

### CODE REVIEW

**Comment by puddly** [comment]
For posterity, here is the "I want to beta test every IKEA update" config:

```yaml
zha:
  zigpy_config:
    ota:
      extra_providers:
        - type: ikea  # default DIRIGERA feed
        - type: ikea
          url: http://fw.ota.homesmart.ikea.net/feed/version_info.json  # HTTPS doesn't work
```

**Comment by MattWestb** [comment]
We shall deleting **all** links to the very old test feed: `https://fw.test.ota.homesmart.ikea.net/feed/version_info.json` then is VERY outdated  and i not used for years and only making problems for user getting outdated OTA for some devices.

**Comment by MattWestb** [comment]
I have problem getting local OTA file working with:

```
    ota:
      enabled: true
      extra_providers:
        - type: z2m
        - type: advanced
          warning: I understand I can *destroy* my devices by enabling OTA updates from files. Some OTA updates can be mistakenly applied to the wrong device, breaking it. I am consciously using this at my own risk.
          path: /config/zigpy_ota
```
Getting 2 different errors then trying fixing the key error:
First "warning" not exist and `voluptuous.error.MultipleInvalid: required key not provided @ data['ota']['extra_providers'][1]['warning'` (example is trounced) and then  fixed the key is unexpected `TypeError: BaseOtaProvider.__init__() got an unexpected keyword argument 'warning'`.

Pleas  post one working config for it and also updating the  documentation  to current code base.


Thanks i advance !!!

**Comment by MattWestb** [comment]
Was tasting the "warning" and if changing it its complaining = OK.
So must being the path.

The config  is now:

```
        - type: advanced
          warning: I understand I can *destroy* my devices by enabling OTA updates from
            files. Some OTA updates can be mistakenly applied to the wrong
            device, breaking it. I am consciously using this at my own risk.
          path: /config/zigpy_ota
```
and the error:
```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 11:38:14 (1 occurrences)
Last logged: 11:38:14

Error setting up entry Billy RCP for zha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 126, in async_setup_entry
    async with radio_mgr.connect_zigpy_app() as app:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/radio_manager.py", line 182, in connect_zigpy_app
    app = await self.radio_type.controller.new(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 250, in new
    app = cls(config)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bellows/zigbee/application.py", line 81, in __init__
    super().__init__(config)
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 67, in __init__
    self._config = self.SCHEMA(config)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 590, in validate_sequence
    cval = validate(index_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/config/validators.py", line 144, in cv_ota_provider
    return provider_cls(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/ota/providers.py", line 712, in __init__
    super().__init__(url=None, **kwargs)
TypeError: BaseOtaProvider.__init__() got an unexpected keyword argument 'warning'
```
I using the same path as in the old config that was working OK

So somthing spooky mus being in this  code:
https://github.com/zigpy/zigpy/blob/50d92d12770b8361394a2ca8d2ef68d2ebbfa08e/zigpy/ota/providers.py#L706-L713

**Comment by MattWestb** [comment]
I have putting in this in the config:
```
    ota:
      enabled: true
#      disable_default_providers: [ikea]
#      # Replace all default providers by specifying `providers` instead of `extra_providers`
      extra_providers:
#        - type: salus 
#          url: https://example.org/salus.json
#          override_previous: true  # Replace all previous Salus providers with this one
        - type: ikea  # DIRIGERA feed
#        - type: ikea  # Old IKEA test feed
#          url: https://fw.test.ota.homesmart.ikea.net/feed/version_info.json
        - type: ikea  # Old IKEA feed
          url: https://fw.ota.homesmart.ikea.net/feed/version_info.json
#        - type: zigpy
#          url: https://example.org/ota.json
#          manufacturer_ids: [0x1234, 0x5678]  # Optional
        - type: z2m
#        - type: z2m  # Use multiple providers of the same type
#          url: https://some/other/index.json
#        - type: z2m_local
#          path: /path/to/index.json
        - type: advanced
          warning: I understand I can *destroy* my devices by enabling OTA updates from
            files. Some OTA updates can be mistakenly applied to the wrong
            device, breaking it. I am consciously using this at my own risk.
          path: /config/zigpy_ota
```
and its loading OK and no errors.
I hope i getting  the TF and DG feed plus the very dangerous Z2M with it.
Shall looking if the system is finding some updates or rolling back the Styrbar from 2.4.19 that i was doing with local files before the system update (reporting back in one or 2 days if being  strange things).

## One more great thanks for great  work done our Puddly !!

PS: documentation is not updated and also the zigpy wiki that can helping users with "OTA problems" but i think its out of my scope fixing.

**Pull request merged**
