### PR TITLE
Third Reality OTA provider

### PR DESCRIPTION
**Pull request by puddly**
Supersedes #1089

```yaml
zha:
  zigpy_config:
    ota:
      thirdreality_provider: true
```

The only device I have been able to update easily is the temperature and humidity sensor; everything else aborts part way through:

```
Ota:upgrade_end(status=<Status.ABORT: 149>, manufacturer_code=4659, image_type=54181, file_version=18)
```

If I re-send the OTA image notification, the device again begins the upgrade where it left off but it only completes about 5-10% each time. If I restart the OTA upgrade 10-20 times, it will eventually complete. This behavior has been consistent for every single device I have tested, with the exception of the temperature and humidity sensor, which completed the entire OTA upgrade in one go.

@hwzolin

### CODE REVIEW

**Comment by puddly** [comment]
The base code works and the devices will eventually update in the background as they periodically check in and resume the previous transfer. I'm merging this PR; once OTA handling is handled per-device in the future, perhaps this nonstandard behavior can be handled gracefully.

**Comment by hwzolin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            That's great news，thank you! I will sync with my colleagues.
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        11/10/2022 06:17
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [zigpy/zigpy] Third Reality OTA provider (PR #1096)
        
      
    
  
  
The base code works and the devices will eventually update in the background as they periodically check in and resume the previous transfer. I'm merging this PR; once OTA handling is handled per-device in the future, perhaps this nonstandard behavior can be handled gracefully.

**Comment by superbaymax1201** [comment]
How can I upgrade my Temperatur and Humidity Sensor to the latest version?

**Comment by hwzolin** [comment]
> How can I upgrade my Temperatur and Humidity Sensor to the latest version?

@puddly

**Comment by puddly** [comment]
@hwzolin @superbaymax1201 There is no easy way to perform OTA updates since your device do not appear to ask for OTA updates every 24 hours like most others. User-initiated OTA updates will be included in a future release.

---

For now, add the above configuration to your Home Assistant `configuration.yaml` file and then restart HA.

Then, issue a Zigbee "Image Notify" command:

image

If it is a device with broken OTA, it will take a few hours for it to repeatedly restart the OTA upgrade. If it is the temperature/humidity sensor, it will finish after 20 minutes. You will then have to reconfigure the device to re-bind the broken clusters.

image

**Pull request merged**
