### PR TITLE
Add a neighbor field in NetworkState object

### PR DESCRIPTION
**Pull request by Adminiuga**
An attempt was made to address https://github.com/zigpy/zigpy-znp/pull/85 comments

@puddly for visibility. Would something like this work for ZNP?

### CODE REVIEW

**Comment by puddly** [comment]
If we're going with a single list, can you add an `is_child` flag or something to the `NodeInfo` class so that we can tell apart children with APS keys?

**Comment by Adminiuga** [comment]
I was thinking that APS Key would go into `NetworkInformation.key_table` and children (or just peer) would go into `neighbor_table` and based on `NodeInfo,logical_type` you can differentiate between children end_devices and routers/coordinators.

**Comment by puddly** [comment]
You're right, that works. This looks good to me.

**Comment by puddly** [comment]
No, just ones with APS link keys. Z-Stack doesn't keep track of logical types at all. Every device with an APS link key needs a corresponding entry in the Z-Stack address manager table, which requires NWK and IEEE addresses.

**Comment by puddly** [comment]
There seems to be a way to query this stuff with EZSP but it didn't return any results with my tiny test network with a HUSBZB-1: https://github.com/puddly/bellows/blob/puddly/open-coordinator-backup/bellows/cli/backup.py#L114

**Pull request merged**
