### PR TITLE
Allow configuration of IKEA update URL

### PR DESCRIPTION
**Pull request by Adminiuga**
Allow configuration of IKEA update URL via `ikea_update_url` configuration parameter.
For example in Home Assistant core `configuration.yaml` add:

```yaml
zha:
  zigpy_config:
    ota:
      ikea_provider: true
      ikea_update_url: http://fw.test.ota.homesmart.ikea.net/feed/version_info.json
```

### CODE REVIEW

**Comment by MattWestb** [comment]
Thanks cod master !!!

I was downgrading oncontroll outlet in deCONZ to 10005777-4.1-TRADFRI-control-outlet-2.0.024.ota.ota and then deleting it in deCONZ and pairing it in ZHA.

First I was putting the same OTA file in the /config/zigpy_ota and restarting ZHA and it was not updating the plug.
Then adding the normal  "ikea_provider: true" and its downloading but throwing the invalid OTA file and not sending it to the device.
Then putting one 2.0.024 OTA file from deCONZ in the ots folder and restating ZHA and repower the plug. Its starts updating and I disconnecting it for more testing.
Deleting the 2.0.024 nd adding    ikea_update_url: http://fw.test.ota.homesmart.ikea.net/feed/version_info.json

Restarting ZHA and repower the plug and its starting the update OK.


Great work done !!!

Only missing possibility forcing loafing of one older version of OTA files theru folder load and config parameter like:

````
zha:
  zigpy_config:
    ota:
      override_with_local_version: true
````

**Comment by puddly** [comment]
"`override_with_local_version: true`" should be the default behavior as of https://github.com/zigpy/zigpy/pull/505.

Are you 100% sure you have the correct OTA file for the device? The broken image from the IKEA website will not even be considered so if the local one isn't being picked up it may be a problem with the file (or the file-based loader is having problems unwrapping the IKEA container).

**Comment by MattWestb** [comment]
I have old OTA files that was downloaded in deCONZ and is working (and the test json is also working).
For the same version (server / local) its working, i have trying with the same version and the ZHA is starting sending the local file to the device.

My proposal is that having one older (lower version) local OTA file and sending it to the device and doing one "downgrade" as its possible in deCONZ. 

Then having the 2.0.022 in the local OTA folder the device is getting the 2.0.024 from the test server = good for "normal" users but not for advance testing.
Also if the device is on 2.0.024 and the local is 2.0.022 its not getting the "downgrade" OTA.

Perhaps i should caling the config parameter "force_version_downgrade" or "override_device_version".

Its only one proposal and if i really need doing it I can doing it in deCONZ (that have losing all devices lats week and Bellows have getting all of them).

**Comment by MattWestb** [comment]
@walthowd  I was putting the `ikea_update_url:` in the wiki but was not changing the text so much.
Can you taking one look so i did not destroying you work !!!

**Comment by walthowd** [comment]
Yup, looks great! What we really need now is someone to host a IKEA update URL somewhere that only has *working* firmware in it!

**Comment by MattWestb** [comment]
For the moment is it not necessary then only IKEA GW and the new scene shortcut button (no update only new device) have being added from the last good ones in the test URL and the all other is at production standard. I finding it interesting wath is happening little later if IKEA is releasing one new GW and locking all updates to their end devices or is fixing bad data setting in the devices (with patch commands for the user data) or if its only corrupted / damaged files on the server.

Great working done !!!

**Pull request merged**
