### PR TITLE
Update ZCL with changes from v7 spec

### PR DESCRIPTION
**Pull request by puddly**
Notable additions:

 - `enhanced` color operations
 - global `attr_reporting_status` (0xFFFE) attribute. Not sure if it's actually used yet but it can now appear in attribute reports.
 - `start_up_on_off` and `start_up_current_level` attributes, which control the power-on behavior of devices.
 - new optional parameters are now documented, which should also fix the various IKEA remote deserialization warnings
 - I've named a bunch of enums and bitmaps in various clusters

### CODE REVIEW

**Comment by puddly** [comment]
I would also like to slowly migrate all command schemas to dictionaries. It's really difficult to figure out what each parameter maps to from just a tuple of types. Should also improve readability for applications making ZCL requests.

**Comment by MattWestb** [comment]
Im very sorry but i gave bot getting / finding one ZCL V8 :-(((

Thanks !!

**Comment by MattWestb** [comment]
This command i cant getting working with cluster commands (ZHA dont have enough fealds 2) then i cant putting all information that is needed.
```
    server_commands = {
        0x0000: (
            "add",
            (t.uint16_t, t.uint8_t, t.uint16_t, t.CharacterString),
            (t.uint16_t, t.uint8_t, t.uint16_t, t.LimitedCharString(16)),
            False,
        ),  # + extension field sets
```
The wireshark is showing how is being done in IKEA GW:
```
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x11)
    Sequence Number: 37
    Command: Add Scene (0x00)
    Payload, String: 
        Group ID: 0x002a
        Scene ID: 0x00
        Transition Time: 1 seconds
        Length: 0
        String: 
        Extension field set 1
            Cluster: On/Off (0x0006)
            On/Off: 1
        Extension field set 2
            Cluster: Color Control (0x0300)
            Color X: 0,4580
            Color Y: 0,4100
```

**Comment by puddly** [comment]
Every ZCL command and response parameter has been named and is accessible from the command definition as a `t.Struct` subclass:

```Python
>>> OnOff(None).server_commands[0x40].schema.fields  # accessing by command ID is a little clunky
[StructField(name='effect_id', type=<enum 'OffEffectIdentifier'>, requires=None, optional=False),
 StructField(name='effect_variant', type=<class 'zigpy.types.basic.uint8_t'>, requires=None, optional=False)]

>>> await ep.on_off.off_with_effect(effect_id=1, effect_variant=2)
```

For now only requests support keyword arguments but I might be able to hack in support in responses via something like a namedtuple, to preserved backwards compatibility for existing code that doesn't reconstruct the response type (like a quirk).

**Comment by dmulcahey** [comment]
wow this is looking really good. 

```
>>> off_with_effect.schema.fields
[StructField(name='effect_id', type=<enum 'OffEffectIdentifier'>, requires=None, optional=False),
 StructField(name='effect_variant', type=<class 'zigpy.types.basic.uint8_t'>, requires=None, optional=False)]

```

this will make fixing the commands in the manage clusters dialog fairly easy.

**Comment by dmulcahey** [comment]
> ```python
> >>> await ep.on_off.off_with_effect(effect_id=1, effect_variant=2)
> ```
> 
> 
> For now only requests support keyword arguments but I might be able to hack in support in responses via something like a namedtuple, to preserved backwards compatibility for existing code that doesn't reconstruct the response type (like a quirk).
> ```

For these... are there enums for the values of the kwargs? should we try to add enums or should we define constants for a lot of the places where tables exist in the spec? This will make the code more readable IMO. that way, in the case above, you won't have to look up what the values `effect_id=1, effect_variant=2` are to understand what the code is doing. Thoughts?

**Comment by puddly** [comment]
The effect identifier is typed (and will be converted when creating a request), I was just lazy when writing the example:

```Python
await ep.on_off.off_with_effect(effect_id=OnOff.OffEffectIdentifier.Dying_Light, effect_variant=2)
```

The effect variant is more complicated and I didn't fill out when scanning through the spec, since its value depends on the effect ID: 

| Effect Identifier Field Value | Effect Variant Field Value | Description |
|  ---------------------------- | -------------------------- | ------------ |
| 0x00 | 0x00 (default) | Fade to off in 0.8 seconds |
|      | 0x01 | No fade |
|      | 0x02 | 50% dim down in 0.8 seconds then fade to off in 12 seconds |
|      | 0x03 to 0xff | Reserved |
| 0x01 | 0x00 (default) | 20% dim up in 0.5s then fade to off in 1 second |
|      | 0x01 to 0xff | Reserved |
| 0x02 to 0xff | 0x00 to 0xff | Reserved |

**Comment by puddly** [comment]
Continuing the schema stuff, I've migrated all of the ZCL attributes from plain tuples to a dedicated type that's created during subclassing.

All command and attribute definitions now hold whether or not they are manufacturer-specific. This removes the need for the `manufacturer_attributes`, `manufacturer_server_commands`, and `manufacturer_client_commands` and the magic surrounding merging them into their respective dictionaries, making the `CustomCluster` subclasses more straightforward.

For simplicity, manufacturer-specific attributes can be defined as a three-tuple, with the last field indicating whether or not the attribute is manufacturer-specific (if the `foundation.ZCLAttributeDef` constructor is too verbose):

```Python
class MyCluster(CustomCluster, OnOff):
    attributes = OnOff.attributes.copy()
    attributes[0x1233] = ("name1", t.uint8_t)  # non-manufacturer-specific
    attributes[0x1234] = ("name2", t.uint8_t, True)  # manufacturer-specific

    client_commands = OnOff.client_commands.copy()
    client_commands[0x12] = foundation.ZCLCommand(
    	name="name3",
    	schema={"param1": t.uint8_t, "optional2?": t.uint16_t},
    	is_reply=False,
    	is_manufacturer_specific=True,
    )

assert MyCluster.attributes_by_name["name1"] is MyCluster.attributes[0x1233]
assert MyCluster.attributes_by_name["name1"].id == 0x1233
assert MyCluster.attributes_by_name["name2"].is_manufacturer_specific
```

All commands are stored either in `MyCluster.client_commands` or `MyCluster.server_commands` and all attributes are in `MyCluster.attributes`, with `MyCluster.attributes_by_name` providing a lookup table that maps to the attribute object itself (not the id!).

**Comment by MattWestb** [comment]
Need testing your fix or is it false safe ?

**Comment by puddly** [comment]
I think it's the fix for the problem you experienced but I will check on a new test network to be sure.

**Comment by MattWestb** [comment]
I was trying sending little toggle to the same light but i dont  getting the warning without the fix so its looks not being easy triggering it.
Perhaps changing CT or color is better way.

I trying little more on the patches system without the fix and see if i can getting the problem triggered.

**Comment by puddly** [comment]
The warnings are intentional, they're just saying what parts of ZHA need to be changed to use the new attribute-based command and attribute definitions:

```Python
# Old way
command_def[0]

# New way
command_def.name
```

**Comment by MattWestb** [comment]
I have problem with the IKEA CWS.
On / Off and Light level is OK.
Changing RGB or TC is giving in the log:
```
0x6c21:1:0x0006] ZCL header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=88, command_id=11, *is_reply=1)
[0x6C21:1:0x0006]: executed 'on' command with args: '()' kwargs: '{}' result: Default_Response(command_id=1, status=<Status.SUCCESS: 0>)
light.ikea_e27_cws_806lm_level_light_color_on_off: turned on: {'on_off': Default_Response(command_id=1, status=<Status.SUCCESS: 0>)}
```
I have restarting HA and also re powered the bulb (it can being its fault then ZHA is sending the wrong  command).

Can you controlling color of your lights ?

I is not getting any errors in the log but i have getting the light  changing its color.

**Comment by MattWestb** [comment]
Sorry HA error log was little slow i have getting more errors:
```
Logger: zigpy.util
Source: /usr/local/lib/python3.9/site-packages/zigpy/util.py:49
First occurred: 20:07:48 (1 occurrences)
Last logged: 20:07:48

Error calling listener.cluster_command: 'ZCLCommandDef' object is not subscriptable



Logger: homeassistant.components.websocket_api.http.connection
Source: components/zha/api.py:631
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:05:27 (1 occurrences)
Last logged: 20:05:27

[139758704517616] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 631, in websocket_device_cluster_commands
    ATTR_NAME: commands[CLUSTER_COMMANDS_SERVER][cmd_id][0],
TypeError: 'ZCLCommandDef' object is not subscriptable



Logger: homeassistant.components.websocket_api.http.connection
Source: components/zha/core/device.py:556
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:05:21 (2 occurrences)
Last logged: 20:05:21

[139758704517616] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 568, in websocket_device_cluster_attributes
    attributes = zha_device.async_get_cluster_attributes(
  File "/usr/src/homeassistant/homeassistant/components/zha/core/device.py", line 563, in async_get_cluster_attributes
    cluster = self.async_get_cluster(endpoint_id, cluster_id, cluster_type)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/device.py", line 556, in async_get_cluster
    return clusters[endpoint_id][cluster_type][cluster_id]
KeyError: 6
```
I restarting the other test network that is using the same docker image an is having more lights and see how it working.

**Comment by MattWestb** [comment]
Was testing requesting OTA updates (2 times) from one IKEA GU10 WS with normal `image_notify (id: 0x0000)` and is getting:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/zha/core/device.py:638
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:05:59 (2 occurrences)
Last logged: 12:06:11

[140506425279776] Value for field 'payload_type' is required
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 737, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 1059, in issue_zigbee_cluster_command
    response = await zha_device.issue_cluster_command(
  File "/usr/src/homeassistant/homeassistant/components/zha/core/device.py", line 638, in issue_cluster_command
    response = await cluster.client_command(command, *args)
  File "/usr/local/lib/python3.9/site-packages/zigpy/zcl/__init__.py", line 308, in reply
    payload = schema(*args, **kwargs).serialize()
  File "/usr/local/lib/python3.9/site-packages/zigpy/types/struct.py", line 196, in serialize
    for field, value in self.assigned_fields(strict=True):
  File "/usr/local/lib/python3.9/site-packages/zigpy/types/struct.py", line 174, in assigned_fields
    raise ValueError(f"Value for field {field.name!r} is required")
ValueError: Value for field 'payload_type' is required
```
Looks like ZHA need getting updated with new matrix for the commands / attributes :-((

**Comment by puddly** [comment]
> Looks like ZHA need getting updated with new matrix for the commands / attributes :-((

Yeah, I think that command is being sent incorrectly. The payload type and query jitter do not appear to be optional (though it seems like some devices accept it anyways):

image

I've been running this PR for a few days now and @dmulcahey has tested it as well (with an updated [HA Core branch](https://github.com/puddly/core/tree/puddly/zigpy-zclv7)). No problems so far.

My main concern is with Tuya devices. If anyone has them to test out, I've updated my HA Core branch to use the `git+` URLs for the component dependencies so you should be able to test it out by:

 - copying `components/zha` from my [HA Core branch](https://github.com/puddly/core/tree/puddly/zigpy-zclv7)
 - adding `"version": "1.0.0",` to the `manifest.json` file
 - and adding it as a custom component.

**Comment by dumpfheimer** [comment]
I replaced the zha component folder (hope that wasn't a mistake) and did have iissues:

All of my Tuya smart plugs remained unavailable, but also a few lights (Tradfri lights). I got nervous and switched back to the original zha component but they have not come back since.

Will wait to see if things back up and check in again

**Comment by dumpfheimer** [comment]
Looks like after some time or if I power cycle them they come back up. If the debug logs are of any use to you let me know.

**Comment by puddly** [comment]
I use Trådfri lights and had no issues so it may have been a configuration or installation problem. Do the debug logs show any issues other than delivery errors?

**Comment by dumpfheimer** [comment]
Anything specific I could look for?

**Comment by dumpfheimer** [comment]
By just scanning over the logs I can't find anything. I'll give your branch another try

**Comment by puddly** [comment]
If you can't see anything in the logs, feel free to email them to me and I can take a look.

**Comment by dumpfheimer** [comment]
Same problem. Tuya smart plugs become unavailable (and stay unavailable after power cycle). I get a bunch of these: Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=10, SrcAddr=0x5049, SrcEndpoint=1, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=76, SecurityUse=<Bool.false: 0>, TimeStamp=12848924, TSN=0, Data=b'\x00\xAD\x00\x07\x00', MacSrcAddr=0x5049, MsgResultRadius=29)
2022-01-28 21:21:12 WARNING (MainThread) [zigpy_znp.zigbee.application] Received an AF message from an unknown device: 0x5049

**Comment by dumpfheimer** [comment]
I may have found something (what a difference a PC makes over a smartphone..)

n 28 21:28:19 server run.sh[1024550]: 2022-01-28 21:28:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140429933549024] Error handling message: Unknown error
Jan 28 21:28:19 server run.sh[1024550]: Traceback (most recent call last):
Jan 28 21:28:19 server run.sh[1024550]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
Jan 28 21:28:19 server run.sh[1024550]:     await func(hass, connection, msg)
Jan 28 21:28:19 server run.sh[1024550]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/zha/api.py", line 695, in websocket_read_zigbee_cluster_attributes
Jan 28 21:28:19 server run.sh[1024550]:     str(success.get(attribute)),
Jan 28 21:28:19 server run.sh[1024550]: AttributeError: 'NoneType' object has no attribute 'get'

**Comment by puddly** [comment]
@dumpfheimer `APPARENT_POWER = "apparent_power"` was added to HA dev on December 23 so it could be that this branch of ZHA will only be compatible with the absolute latest HA dev or one of the recent betas (e.g. `2022.2.0b2`).

**Comment by dumpfheimer** [comment]
Looking good!

A few things are still messed up from my exhibition back to zigpy 0.26 but I re paired a Tuya smart plug and it seems to be working fine!

**Comment by dumpfheimer** [comment]
Oh man, okay. So I should have done the custom component. After updating HA it overwrote the component from your branch. 

Now I actually get an error:

```
2022-01-28 23:29:33 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ZZH! for zha
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/zha/__init__.py", line 99, in async_setup_entry
    setup_quirks(config)
  File "/srv/homeassistant/lib/python3.9/site-packages/zhaquirks/__init__.py", line 400, in setup
    importlib.import_module(modname)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/srv/homeassistant/lib/python3.9/site-packages/zhaquirks/centralite/__init__.py", line 11, in <module>
    class CentraLiteAccelCluster(CustomCluster):
  File "/srv/homeassistant/lib/python3.9/site-packages/zigpy/zcl/__init__.py", line 26, in __init__
    cls.attridx: Dict[str, int] = {
  File "/srv/homeassistant/lib/python3.9/site-packages/zigpy/zcl/__init__.py", line 27, in <dictcomp>
    attr_name: attr_id for attr_id, (attr_name, _) in cls.attributes.items()
ValueError: too many values to unpack (expected 2)
```

I believe it is time for me to go to bed before I make things worse.

**Comment by puddly** [comment]
I think something is broken with dependencies, `cls.attridx` doesn't exist any more in this branch of zigpy. I'll see what I can do about making this easier to test out.

**Comment by dumpfheimer** [comment]
Ah, yes. Looks like the requirements are not being installed correctly on my machine

**Comment by dumpfheimer** [comment]
Got it. The dependency is git+https://github.com/puddly/zigpy.git@puddly/zclv7#zigpy==0.44.0.dev0 but I actually had 0.44.0.dev0 installed from the zigpy/zigpy branch which made pip skip the git install

**Comment by dumpfheimer** [comment]
Pip is convinced your dependencies are installed, HA is up and running and the Tuya switches are switching 👍

**Comment by dumpfheimer** [comment]
It seems like hue lamps are not reporting back immediately that they have been turned on/off. They do in fact change their state immediately but it takes about 30s for the state in HA to update accordingly

**Comment by MattWestb** [comment]
Philips HUE device is no doing reporting they must being pulled from the host system for getting status updated in ZHA (= not Zigbee standard way).

**Comment by MattWestb** [comment]
I think then sending command from ZHA the system is pulling the state some seconds after the command is being sent but if doing changes "local" (with bounded remote) it can taking long time before ZHA is pulling the device state (I think for color ist around up to 45 minutes).

**Comment by dumpfheimer** [comment]
I am controlling the lights solely over HA. This definitely was different before. It immediately reported the new state. I do not know how that happened internally but the user experience imho was better.

**Comment by dumpfheimer** [comment]
In the logs, in the first seconds after toggling, I only see the "off request" and one response. If there should be a follow-up request checking the state I think something might be wrong.

**Comment by MattWestb** [comment]
Look if you is getting some trace in the debug log.
I think the pulling can being broked of our Puddlys dream coding (I hope hi is sleeping well now and dont doing too much nightmare coding) ;-))

Great coding done and also testing !!!

**Comment by dumpfheimer** [comment]
Completely agree, great coding, thank you, @puddly !!

None of this is meant as a complaint of any sort. I only wanted to provide feedback and help testing.

**Comment by MattWestb** [comment]
I have doing one round with Puddly but im fighting getting tuya TS004F remotes working and getting leave with rejoin flag working (with help of **P**) and have my production system in debug then its have problem with automations with ZHA devices is not working 100% so i cant messing it more up with testing the ZCL R7 this round.

Testing is very important for getting the system working OK for all user then doing code changes so not braking our users system and they is getting very sad.

**Comment by dumpfheimer** [comment]
I have quite a few Ikea remote controls and it seems like all of the buttons except the on off button stopped working. Is this a possible issue with the branch or more likely a problem with the home assistant beta?

**Comment by puddly** [comment]
This change only messes with serialization and deserialization of ZCL commands. If there is a bug in this huge PR causing your problem, you should still see the radio library log something when you press a button on the remote and then zigpy not properly parse it.

**Comment by dumpfheimer** [comment]
I do see log messages when I press one of the buttons:

```
2022-01-29 21:00:41 DEBUG (MainThread) [zigpy.zcl] [0x359B:1:0x0005] Received ZCL frame: b'\x05\x7C\x11\x49\x07\x00\x01\x0D\x00'
2022-01-29 21:00:41 DEBUG (MainThread) [zigpy.zcl] [0x359B:1:0x0005] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=True, is_reply=0, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), manufacturer=4476, tsn=73, command_id=7, *is_reply=0)
2022-01-29 21:00:41 DEBUG (MainThread) [zigpy.zcl] [0x359B:1:0x0005] Decoded ZCL frame: press(param1=256, param2=13, param3=0)
2022-01-29 21:00:41 DEBUG (MainThread) [zigpy.zcl] [0x359B:1:0x0005] Received command 0x07 (TSN 73): press(param1=256, param2=13, param3=0)
2022-01-29 21:00:41 DEBUG (MainThread) [zigpy.zcl] [0x359B:1:0x0005] No explicit handler for cluster command 0x07 press(param1=256, param2=13, param3=0)
```

**Comment by puddly** [comment]
That looks fine. Can you enable ZHA debug logging as well and see what happens to this frame after it's received?

**Comment by dumpfheimer** [comment]
I enabled them but got no followup messages. I do however get other DEBUG level messages from zha now so it seems to be enabled. I believe this might be an issue with the quirks, because all buttons result in a zha_event

**Comment by dumpfheimer** [comment]
I will take a few minutes and setup HA from scratch just to be sure nothing is messed up here

**Comment by dumpfheimer** [comment]
I think I may have found the issue. This is the event in which the button press results:
`2022-01-29 22:19:19 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event zha_event[L]: device_ieee=00:0d:6f:ff:fe:51:40:56, unique_id=00:0d:6f:ff:fe:51:40:56:1:0x0005, device_id=0f24534a6001da50ea6546d50d49990a, endpoint_id=1, cluster_id=5, command=press, args=press(param1=256, param2=13, param3=0)>`

If I look at the quirk, I would assume this is the matching device "action": 

```
        (SHORT_PRESS, RIGHT): {
            COMMAND: COMMAND_PRESS,
            CLUSTER_ID: 5,
            ENDPOINT_ID: 1,
            ARGS: [256, 13, 0],
        },

```

But the value of `SHORT_PRESS` actually is "short_press" instead of "press" like in the event.

**Comment by dumpfheimer** [comment]
I got nowhere with this yesterday, but realized I need a separate HA somewhere for testing so I don't mess up the house, and the logs are not full with spam. As soon as that's up I hope I can see a difference in the logs and will check if something changes in the resulting event.

**Comment by dumpfheimer** [comment]
Just so you know, I reverted zigpy and zigpy_znp back to development state (git) and zhaquirks to the HA default and the remote controls started working again and the light states change instantaneously. Hope I can tell you more tomorrow with my test setup.

**Comment by dumpfheimer** [comment]
I was now able to test with a clean HA setup. Here are the logs, 2x2 parts: using ZCL7 and default zigpy and pressing the toggle switch (which works) and pressing the right button (which does not work):

```
ZCL7:

TOGGLE:
2022-01-30 22:15:45 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=6, SrcAddr=0xBED8, SrcEndpoint=1, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=160, SecurityUse=<Bool.false: 0>, TimeStamp=15215934, TSN=0, Data=b'\x01\x27\x02', MacSrcAddr=0xBED8, MsgResultRadius=29)
2022-01-30 22:15:45 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0006] Received ZCL frame: b'\x01\x27\x02'
2022-01-30 22:15:45 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=0, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=39, command_id=2, *is_reply=0)
2022-01-30 22:15:45 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0006] Decoded ZCL frame: toggle()
2022-01-30 22:15:45 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0006] Received command 0x02 (TSN 39): toggle()
2022-01-30 22:15:45 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0006] No explicit handler for cluster command 0x02 toggle()
2022-01-30 22:15:45 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event zha_event[L]: device_ieee=d0:cf:5e:ff:fe:f0:68:cb, unique_id=d0:cf:5e:ff:fe:f0:68:cb:1:0x0006, device_id=a69ea7d92ffa4dd6f758ca807f1b729d, endpoint_id=1, cluster_id=6, command=toggle, args=toggle()>
2022-01-30 22:15:45 DEBUG (MainThread) [homeassistant.components.automation.test_remote_automation] Automation triggered by event 'zha_event'
2022-01-30 22:15:45 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event automation_triggered[L]: name=Test Remote Automation, entity_id=automation.test_remote_automation, source=event 'zha_event'>
2022-01-30 22:15:47 DEBUG (MainThread) [zigpy_znp.api] Sending request: SYS.Ping.Req()
2022-01-30 22:15:47 DEBUG (MainThread) [zigpy_znp.api] Received command: SYS.Ping.Rsp(Capabilities=<MTCapabilities.APP_CNF|GP|UTIL|ZDO|AF|SYS: 1625>)


RIGHT:
2022-01-30 22:16:04 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=5, SrcAddr=0xBED8, SrcEndpoint=1, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=163, SecurityUse=<Bool.false: 0>, TimeStamp=677490, TSN=0, Data=b'\x05\x7C\x11\x28\x07\x00\x01\x0D\x00', MacSrcAddr=0xBED8, MsgResultRadius=29)
2022-01-30 22:16:04 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0005] Received ZCL frame: b'\x05\x7C\x11\x28\x07\x00\x01\x0D\x00'
2022-01-30 22:16:04 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0005] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=True, is_reply=0, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), manufacturer=4476, tsn=40, command_id=7, *is_reply=0)
2022-01-30 22:16:04 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0005] Decoded ZCL frame: press(param1=256, param2=13, param3=0)
2022-01-30 22:16:04 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0005] Received command 0x07 (TSN 40): press(param1=256, param2=13, param3=0)
2022-01-30 22:16:04 DEBUG (MainThread) [zigpy.zcl] [0xBED8:1:0x0005] No explicit handler for cluster command 0x07 press(param1=256, param2=13, param3=0)
2022-01-30 22:16:04 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event zha_event[L]: device_ieee=d0:cf:5e:ff:fe:f0:68:cb, unique_id=d0:cf:5e:ff:fe:f0:68:cb:1:0x0005, device_id=a69ea7d92ffa4dd6f758ca807f1b729d, endpoint_id=1, cluster_id=5, command=press, args=press(param1=256, param2=13, param3=0)>



NORMAL:
TOGGLE:
2022-01-30 22:28:36 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=6, SrcAddr=0xBED8, SrcEndpoint=1, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=153, SecurityUse=<Bool.false: 0>, TimeStamp=855163, TSN=0, Data=b'\x01\x2D\x02', MacSrcAddr=0xBED8, MsgResultRadius=29)
2022-01-30 22:28:36 DEBUG (MainThread) [zigpy.zcl] [0xbed8:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=False disable_default_response=False> manufacturer=None tsn=45 command_id=2>
2022-01-30 22:28:36 DEBUG (MainThread) [zigpy.zcl] [0xbed8:1:0x0006] ZCL request 0x0002: []
2022-01-30 22:28:36 DEBUG (MainThread) [zigpy.zcl] [0xbed8:1:0x0006] No handler for cluster command 2
2022-01-30 22:28:36 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event zha_event[L]: device_ieee=d0:cf:5e:ff:fe:f0:68:cb, unique_id=d0:cf:5e:ff:fe:f0:68:cb:1:0x0006, device_id=a69ea7d92ffa4dd6f758ca807f1b729d, endpoint_id=1, cluster_id=6, command=toggle, args=[]>
2022-01-30 22:28:36 DEBUG (MainThread) [homeassistant.components.automation.test_remote_automation] Automation triggered by event 'zha_event'
2022-01-30 22:28:36 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event automation_triggered[L]: name=Test Remote Automation, entity_id=automation.test_remote_automation, source=event 'zha_event'>

RIGHT:
2022-01-30 22:28:49 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=5, SrcAddr=0xBED8, SrcEndpoint=1, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=153, SecurityUse=<Bool.false: 0>, TimeStamp=1716879, TSN=0, Data=b'\x05\x7C\x11\x2E\x07\x00\x01\x0D\x00', MacSrcAddr=0xBED8, MsgResultRadius=29)
2022-01-30 22:28:49 DEBUG (MainThread) [zigpy.zcl] [0xbed8:1:0x0005] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=True is_reply=False disable_default_response=False> manufacturer=4476 tsn=46 command_id=7>
2022-01-30 22:28:49 DEBUG (MainThread) [zigpy.zcl] [0xbed8:1:0x0005] ZCL request 0x0007: [256, 13, 0]
2022-01-30 22:28:49 DEBUG (MainThread) [zigpy.zcl] [0xbed8:1:0x0005] No handler for cluster command 7
2022-01-30 22:28:49 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event zha_event[L]: device_ieee=d0:cf:5e:ff:fe:f0:68:cb, unique_id=d0:cf:5e:ff:fe:f0:68:cb:1:0x0005, device_id=a69ea7d92ffa4dd6f758ca807f1b729d, endpoint_id=1, cluster_id=5, command=press, args=[256, 13, 0]>
2022-01-30 22:28:49 DEBUG (MainThread) [homeassistant.components.automation.test_remote_automation] Automation triggered by event 'zha_event'
2022-01-30 22:28:49 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event automation_triggered[L]: name=Test Remote Automation, entity_id=automation.test_remote_automation, source=event 'zha_event'>

```

The resulting event in deed is slightly different:
in ZCL i get `args=press(param1=256, param2=13, param3=0)`
but in default I get `args=[256, 13, 0]`

Not sure if this actually is the problem, but I will try to look into why this could be and if there is an easy fix

**Comment by dumpfheimer** [comment]
I found a workaround that fixed the remote control issue for me:
https://github.com/dumpfheimer/zigpy/commit/60addef95f922d42a3869b4248fd72146aa1fc73

Maybe you can make sence of it. Seems like the new argument format (CommandSchema) is not seen as the same as a simple array of values (args in event)

**Comment by puddly** [comment]
Thanks for taking a look. Does the problem come back if you return a tuple instead of a list?

```Python
        return hdr, tuple(response_array)
```

**Comment by dumpfheimer** [comment]
Will get back to you tomorrow, I have already turned everything off

**Comment by dumpfheimer** [comment]
No, `return hdr, tuple(response_array)` does not work

**Comment by dumpfheimer** [comment]
I ended up changing the ZHA integration to only manipulate the structure before sending the HA event to minimize/eliminate the impact on zigpy. I am however completely unsure on how this affects other people or how it plays out in general:

https://github.com/dumpfheimer/core/commits/dumpfheimer/zigpy-zclv7-fix

**Comment by dumpfheimer** [comment]
Looks like your last commit fixed my light-state-not-updating-problem!
With my workaround for the device triggers everything seems to be working.

**Comment by puddly** [comment]
I think this PR is practically done. ZDO commands still are returned without any runtime field names but this can be addressed in a future PR.

Let's get this merged before https://github.com/zigpy/zigpy/pull/905 gets too big. This PR likely fixes many of the problems addressed in that one.

**Comment by MattWestb** [comment]
Also if getting it in dev is easier for user testing it and getting feedback from more diferent system setups.

## Great work done !!!

**Comment by dmulcahey** [comment]
@puddly I say let it rip if you are comfortable

**Comment by Adminiuga** [comment]
+1

**Comment by MattWestb** [comment]
## GREAT !!

**Pull request merged**
