### PR TITLE
Implement packet debouncing

### LINKED ISSUE #671: Multiple frames with the same ZCL counter trigger multiples events
I just bought the IKEA Tradfri shortcut button and when using it, it produces 6 to 7 frames with the same ZCL counter : this has the effect to produce the same amount of events in HA as well. Is this a normal behaviour?

According to [this](https://community.home-assistant.io/t/zha-ikea-tradfri-shortcut-button/261936) thread, not everyone has their remote doing it.

Here’s the device signature : [IKEA Tradfri Shortcut button signature](https://paste.ubuntu.com/p/XGqG5qQgjp/).

Here’s the log : [HA log](https://paste.ubuntu.com/p/wc4Yt9QNz9/).

Also here’s a network capture showing the behaviour : [network capture](https://pasteboard.co/JPp8ddw.png).

I am running HA 2021.2.0 and tried [this quirk](https://github.com/TheJulianJES/zha-device-handlers/blob/ikea_shortcut_button/zhaquirks/ikea/shortcutbtn.py) with a HUSBZB-1.

Thank you for your guidance!

### PR DESCRIPTION
**Pull request by puddly**
Duplicate Zigbee packets received within a 10s window (picked arbitrarily) will be ignored and only the first one will be handled.

Packets are considered duplicates if *everything* about them is the same: same addressing mode, source, destination, payload, etc. This is lower-level than filtering based on TSN alone and should be safer. We can investigate deduplicating based on TSN if this is not enough.

### CODE REVIEW

**Comment by MattWestb** [comment]
Is it also working for broadcast then old devices is sending group commands 3 time and new is not then using passive ack for group frames ?

**Comment by puddly** [comment]
This PR doesn't help with the original Tuya issue in its current form:

```Python
2024-01-05 21:15:20.782 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 1, 6, 5, 15, 20, 782637, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x6BD3), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=202, profile_id=260, cluster_id=61184, data=Serialized[b'\t6\x02\x00\x89m\x02\x00\x04\x00\x00\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=148, rssi=-63)
2024-01-05 21:15:20.993 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 1, 6, 5, 15, 20, 993453, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x6BD3), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=203, profile_id=260, cluster_id=61184, data=Serialized[b'\t6\x02\x00\x89m\x02\x00\x04\x00\x00\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=152, rssi=-62)
2024-01-05 21:15:21.198 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 1, 6, 5, 15, 21, 198261, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x6BD3), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=204, profile_id=260, cluster_id=61184, data=Serialized[b'\t6\x02\x00\x89m\x02\x00\x04\x00\x00\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=152, rssi=-62)
2024-01-05 21:15:21.387 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 1, 6, 5, 15, 21, 387366, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x6BD3), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=205, profile_id=260, cluster_id=61184, data=Serialized[b'\t6\x02\x00\x89m\x02\x00\x04\x00\x00\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=144, rssi=-64)
2024-01-05 21:15:21.599 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 1, 6, 5, 15, 21, 599380, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x6BD3), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=206, profile_id=260, cluster_id=61184, data=Serialized[b'\t6\x02\x00\x89m\x02\x00\x04\x00\x00\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=156, rssi=-61)
2024-01-05 21:15:21.783 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 1, 6, 5, 15, 21, 782985, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x6BD3), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=207, profile_id=260, cluster_id=61184, data=Serialized[b'\t6\x02\x00\x89m\x02\x00\x04\x00\x00\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=148, rssi=-63)
2024-01-05 21:15:21.984 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 1, 6, 5, 15, 21, 984142, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x6BD3), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=208, profile_id=260, cluster_id=61184, data=Serialized[b'\t6\x02\x00\x89m\x02\x00\x04\x00\x00\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=152, rssi=-62)
```

The Tuya devices send these packets nonstop with identical ZCL TSNs but with different packet-level TSNs (I think this attribute is improperly named, it should be `sequence`?). Is this because these are retries that were not APS ACKed due to interference?

It looks like we will have to dig into the ZCL layer after all. Or ignore the packet TSN/sequence?

**Comment by MattWestb** [comment]
If can being the default response that its need in the opposite direction as the TS004F DMS is doing from the extra end points (I have not looking how Z2M have doing but GE was changing the direction i think if remember OK).

**Comment by MattWestb** [comment]
By the way im home (@ Vienna) now and have start updating to 2024.2 and i have time testing later in the week if you need it being done.

**Pull request merged**
