### PR TITLE
Hello, this is the OTA code of thirdreality company. Please check it

### PR DESCRIPTION
**Pull request by hwzolin**
@puddly Hello, this is the OTA code of thirdreality company. Please check it

### CODE REVIEW

**Comment by dmulcahey** [comment]
Install precommit and run the checks. Please address the tagged lint failures

**Comment by puddly** [comment]
@hwzolin I've just tested the latest `1.00.21` firmware for the 3RTHS24BZ temperature/humidity sensor and can confirm that the increased binding table size allows for attribute reporting to be properly configured. Thank you!

I've reverse engineered the OTA image format (https://github.com/zigpy/zigpy/pull/1090) of all of the available images. To save you the trouble of having to implement this PR yourself, can you instead add a few more keys to your JSON:

```diff
 {
   "modelId": "3RSB22BZ",
   "url": "https://tr-zha.s3.amazonaws.com/firmwares/SmartButton_Zigbee_PROD_OTA_V21_1.00.21.ota",
   "version": "1.00.21",
+  "imageType": 54184,
+  "manufacturerId": 4659,
+  "fileVersion": 33
 }
```

These three fields are contained within the Zigbee OTA file header. You can extract them yourself from the parsed header:

```console
$ pip install git+https://github.com/zigpy/zigpy-cli.git
$ pip install git+https://github.com/zigpy/zigpy.git  # need latest version for OTA format decoder
$ zigpy ota info SmartButton_Zigbee_PROD_OTA_V21_1.00.21.ota
Parsing SmartButton_Zigbee_PROD_OTA_V21_1.00.21.ota
Header: OTAImageHeader(upgrade_file_id=200208670, header_version=256, header_length=56, field_control=<FieldControl.0: 0>, manufacturer_id=4659, image_type=54184, file_version=33, stack_version=2, header_string='Telink OTA Sample Usage', image_size=126738, *device_specific_file=False, *hardware_versions_present=False, *key=ImageKey(manufacturer_id=4659, image_type=54184), *security_credential_version_present=False)
Number of subelements: 1
Validation result: ValidationResult.UNKNOWN
```

Let me know when this is done and I can make a PR to add Third Reality OTA support to zigpy.

**Comment by hwzolin** [comment]
@puddly Hello, your suggestion has been dealt with, please check if it meets the requirements.

**Comment by puddly** [comment]
Thank you. There is one problem with the firmware images themselves.

When a device asks for a firmware image, it sends the following query:

```Python
Ota:QueryNextImageCommand(field_control=<FieldControl.0: 0>, manufacturer_code=4659, image_type=54182, current_file_version=268513281)
```

The device's current `sw_build_id` is `v1.00.19`. According to the JSON in your OTA server, the following image is compatible and has a higher version:

```json
{
    "modelId": "3RSP019BZ",
    "url": "https://tr-zha.s3.amazonaws.com/firmwares/SmartPlug_Zigbee_PROD_OTA_V20_v1.00.20.ota",
    "version": "1.00.20",
    "imageType": 54182,
    "manufacturerId": 4659,
    "fileVersion": 32
}
```

However, the new OTA file's `file_version` is `32`, while the current device's version is `268513281` (`0x10013001`). Since the current version is bigger than the file version, the OTA upgrade will not be performed, since it will be considered a downgrade.

Can you make the OTA image file versions (not just what is in the JSON) increasing?

**Comment by hwzolin** [comment]
Can you please tell me how you got the current device version 268513281 (0x10013001)?

**Comment by hwzolin** [comment]
@puddly Can you please tell me how you got the current device version 268513281 (0x10013001)?

**Comment by puddly** [comment]
This is what the device is sending when it begins an OTA upgrade. You send it an OTA "image notify" command, it sends back a "query next image" command, which contains this version number.

**Comment by puddly** [comment]
Closing in favor of #1096.

**Comment by hwzolin** [comment]
@puddly Excuse me, can I update the third reality device on ZHA now?

**Comment by puddly** [comment]
https://github.com/home-assistant/core/pull/82509 did not make it in time for 2022.11.4. Once 2022.11.5 comes out, you can by enabling the OTA provider:

```yaml
zha:
  zigpy_config:
    ota_config:
      thirdreality_provider: true
```

And then notify a device of the new image. Progress will be in the debug log.

**Comment by hwzolin** [comment]
> [home-assistant/core#82509](https://github.com/home-assistant/core/pull/82509) did not make it in time for 2022.11.4. Once 2022.11.5 comes out, you can by enabling the OTA provider:
> 
> ```yaml
> zha:
>   zigpy_config:
>     ota_config:
>       thirdreality_provider: true
> ```
> 
> And then notify a device of the new image. Progress will be in the debug log.

@puddly Ok, I see, thanks.

**Comment by puddly** [comment]
@TheJulianJES Thanks! I've added it to the 2022.11.5 milestone.

**Comment by hwzolin** [comment]
@puddly Hi, I have upgraded HA to version 11.5, but when I was on an OTA device, I still prompted that no OTA image is available. Am I misconfiguring?

**The following pictures are my configuration content, please take a look:**
image_notify
Developer Tools
configuration yaml

**The chart below is the result of OTA：**
update_result

**Comment by puddly** [comment]
The format of the OTA JSON changed and thus the parser for it in 2022.11.5 is not working. You should see an error initializing the OTA provider.

I fixed it a few hours ago https://github.com/zigpy/zigpy/pull/1119 and it is in the current beta https://github.com/home-assistant/core/releases/tag/2022.12.0b0

**Comment by hwzolin** [comment]
> The format of the OTA JSON changed and thus the parser for it in 2022.11.5 is not working. You should see an error initializing the OTA provider.
> 
> I fixed it a few hours ago #1119 and it is in the current beta https://github.com/home-assistant/core/releases/tag/2022.12.0b0

@puddly  
Hello, I have upgraded HA to 2022.12.0. But my OTA for the humidity and temperature sensor still prompts "No OTA image is available".
I'm confused, what's wrong with the configuration? Could you please tell me all the details of your configuration?
OTA_LOG

**Comment by puddly** [comment]
Ah, my mistake! The `ota_config` key should instead be `ota`:

```yaml
zha:
  zigpy_config:
    ota:
      thirdreality_provider: true
```

Here is a log of the temperature sensor updating:

```Python
2022-12-07 21:42:52.736 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA query_next_image handler for 'Third Reality, Inc 3RTHS24BZ': field_control=FieldControl.0, manufacturer_id=4659, image_type=54185, current_file_version=21, hardware_version=None, model='3RTHS24BZ'
2022-12-07 21:42:52.744 DEBUG (MainThread) [zigpy.ota.provider] Downloading https://tr-zha.s3.amazonaws.com/firmwares/TRTL_ThermalSensor_PROD_OTA_V21_1.00.21.ota for ImageKey(manufacturer_id=4659, image_type=54185)
2022-12-07 21:42:53.093 DEBUG (MainThread) [zigpy.ota.provider] Finished downloading from https://tr-zha.s3.amazonaws.com/firmwares/TRTL_ThermalSensor_PROD_OTA_V21_1.00.21.ota for ImageKey(manufacturer_id=4659, image_type=54185) ver 1.00.21
2022-12-07 21:42:53.095 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA image version: 33, size: 124946. Update needed: True
2022-12-07 21:43:07.778 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA query_next_image handler for 'Third Reality, Inc 3RTHS24BZ': field_control=FieldControl.0, manufacturer_id=4659, image_type=54185, current_file_version=21, hardware_version=None, model='3RTHS24BZ'
...
2022-12-07 21:43:42.310 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.0
2022-12-07 21:43:42.529 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.1
2022-12-07 21:43:42.780 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.1
2022-12-07 21:43:43.032 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.1
2022-12-07 21:43:43.273 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.2
2022-12-07 21:43:43.531 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.2
```

**Comment by hwzolin** [comment]
> Ah, my mistake! The `ota_config` key should instead be `ota`:
> 
> ```yaml
> zha:
>   zigpy_config:
>     ota:
>       thirdreality_provider: true
> ```
> 
> Here is a log of the temperature sensor updating:
> 
> ```python
> 2022-12-07 21:42:52.736 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA query_next_image handler for 'Third Reality, Inc 3RTHS24BZ': field_control=FieldControl.0, manufacturer_id=4659, image_type=54185, current_file_version=21, hardware_version=None, model='3RTHS24BZ'
> 2022-12-07 21:42:52.744 DEBUG (MainThread) [zigpy.ota.provider] Downloading https://tr-zha.s3.amazonaws.com/firmwares/TRTL_ThermalSensor_PROD_OTA_V21_1.00.21.ota for ImageKey(manufacturer_id=4659, image_type=54185)
> 2022-12-07 21:42:53.093 DEBUG (MainThread) [zigpy.ota.provider] Finished downloading from https://tr-zha.s3.amazonaws.com/firmwares/TRTL_ThermalSensor_PROD_OTA_V21_1.00.21.ota for ImageKey(manufacturer_id=4659, image_type=54185) ver 1.00.21
> 2022-12-07 21:42:53.095 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA image version: 33, size: 124946. Update needed: True
> 2022-12-07 21:43:07.778 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA query_next_image handler for 'Third Reality, Inc 3RTHS24BZ': field_control=FieldControl.0, manufacturer_id=4659, image_type=54185, current_file_version=21, hardware_version=None, model='3RTHS24BZ'
> ...
> 2022-12-07 21:43:42.310 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.0
> 2022-12-07 21:43:42.529 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.1
> 2022-12-07 21:43:42.780 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.1
> 2022-12-07 21:43:43.032 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.1
> 2022-12-07 21:43:43.273 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.2
> 2022-12-07 21:43:43.531 DEBUG (MainThread) [zigpy.zcl] [0x9253:1:0x0019] OTA upgrade progress: 0.2
> ```

@puddly Thank you for your help. Yesterday I tried many times and was able to OTA devices.

**Comment by hwzolin** [comment]
@puddly Hello, I have the following brands of dongle around me now: nortek, conbe, nxp 5169 (zigate firmware), sonoff. I can't use SONOFF's dongle to OTA Third Reality devices. Do you know how to solve this problem?

**Comment by puddly** [comment]
@hwzolin I've been testing using a Silicon Labs radio like the Sonoff and have had no issues. You really need to provide more context here.

**Pull request closed without merging**
