### PR TITLE
0.5.0 Release.

### PR DESCRIPTION
**Pull request by Adminiuga**
0.5.0 Release

### CODE REVIEW

**Comment by jurriaan** [comment]
I think the connection between GitHub and Travis for this repo is broken. The build is green on Travis: https://travis-ci.org/zigpy/zigpy/builds/544297959

**Comment by Adminiuga** [comment]
> I think the connection between GitHub and Travis for this repo is broken. The build is green on Travis: https://travis-ci.org/zigpy/zigpy/builds/544297959

seems only for master branch (

**Comment by jurriaan** [comment]
It works :tada:

**Comment by Adminiuga** [comment]
yep, just has one extra commit which i did not want, but...

**Pull request closed without merging**
