### PR TITLE
Add Salus OTA update capability

### PR DESCRIPTION
**Pull request by davet2001**
As discussed in #827, this is a work in progress PR for supporting OTA upgrades for Salus devices (sometimes also called "Computime").

The mechanism is quite similar to the existing Ledvance and Ikea updates with one main exception:

Salus provide a `.json` file listing all of the firmware images, but unfortunately these do not contain an `image_id` that can be used to select the correct image as advertised by the device.  Only the header of the ota update (once it is downloaded and extracted) shows this.

All users downloading and extracting every `.tar.gz` file that Salus publish (each time a check is done for FW updates) would be an unfriendly burden on the download server.  So instead this PR adds the model name as an alternative to be used for the key.

In honesty I don't know if this will work for all devices, but it works for mine and it appears that the Salus official FW updates must either be doing this (or another API or a proprietary lookup table).

Hint: you can use something like this in `zigpy/ota/__init__.py`:line66 in order to trigger a FW update that would normally be skipped:
```
        if ver >= self.version:
            print("IGNORING FW UPGRADE VERSION CHECK!")
            # return False
```

Current status is that it works for my devices.

Please comment!

### CODE REVIEW

**Comment by davet2001** [comment]
@Adminiuga Please could you give me a steer whether this approach is acceptable before I go ahead and write test cases?

**Comment by Adminiuga** [comment]
I'm fine with it. 

@puddly  thoughts?

**Comment by puddly** [comment]
Sure.  It's not like we see a new HTTP image provider added every week so while the image key stuff isn't optimal, it works.  When we get around to rewriting OTA entirely to decouple images it from zigpy, we can properly address the underlying zigpy OTA architecture flaws.

Some code changes:

 - Maybe replace the few instances of `4216` with `Salus.MANUFACTURER_ID` for readability, if circular imports don't make it too difficult.
 - Use a context manager to auto-close the `tarfile` object: `with tarfile.open(fileobj=img_tgz) as tar`.

**Comment by davet2001** [comment]
Test coverage should be up to all but 1 line now.

**Comment by puddly** [comment]
You can fix the failing lint stuff by running the pre-commit hook:

```console
$ pip install pre-commit
$ pre-commit install
$ pre-commit run --all-files
```

It'll auto-format your code.

**Comment by davet2001** [comment]
Should be 100% now, with formatting fixed.  Thanks @puddly!

**Comment by Hedda** [comment]
@davet2001 Will you add "Salus/Computime" in the "Zigbee device OTA updates" section of README.md for zigpy?

https://github.com/zigpy/zigpy/blob/dev/README.md#zigbee-device-ota-updates

And maybe update Home Assistant's ZHA docs once a new zigpy release with it is bumped in Home Assistant core?

https://www.home-assistant.io/integrations/zha#ota-firmware-updates

**Comment by davet2001** [comment]
> @davet2001 Will you add "Salus/Computime" in the "Zigbee device OTA updates" section of README.md for zigpy?
> 
> https://github.com/zigpy/zigpy/blob/dev/README.md#zigbee-device-ota-updates
> 
> And maybe update Home Assistant's ZHA docs once a new zigpy release with it is bumped in Home Assistant core?
> 
> https://www.home-assistant.io/integrations/zha#ota-firmware-updates

Both now done.

The [HA docs PR ](https://github.com/home-assistant/home-assistant.io/pull/20638) is a draft since the zigpy version is not bumped yet.

**Comment by davet2001** [comment]
@

**Pull request merged**
